version: '3.7'

volumes:
  node_modules:

services:
  server:
    image: ventup/ventupapi-mock-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 4000:4000
    stdin_open: true
    tty: true
